{
    'name': 'Workshop Register',
    'version': '1.0',
    'summary': 'Manage Workshop Register linked with Suppliers and Products for Aircraft',
    'depends': ['base', 'contacts', 'product', 'hr','web'],
    'author':'Tech Rajendra',
    'data': [
        'data/ir_sequence_data.xml',
        'security/user_groups.xml',
        'views/change_title.xml',
        'views/workshop_register_views.xml',
        'security/ir.model.access.csv',
        'reports/workshop_report_templates.xml',
        'reports/workshop_report.xml',
        'views/access_permission_line.xml',
        'views/requisition_views.xml',
        'reports/requisition_report_template.xml',
        'views/work_order_views.xml',
        'reports/work_order_report.xml',
        'reports/work_order_templates.xml',
        'views/repair_order_views.xml',
        'views/logistic_unserviceable_item.xml',
        'views/logistic_serviceable_item.xml',
        'views/store_requisition_views.xml',
        'reports/repair_order_template.xml',
        'reports/logistics_report.xml',
        'reports/store_requisition_report.xml',
        'reports/logistics_serviceable_report.xml',
        'reports/logistics_unserviceable_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'jss_code/static/src/js/title_patch.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
